sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y qemu-system-x86 unzip
  - sudo apt-get install -y python-pip
  - wget https://releases.hashicorp.com/packer/1.0.3/packer_1.0.3_linux_amd64.zip
  - unzip packer*

script:
  - export PACKER_LOG=1
  - sh install.sh
  - cd bee-image-builder
  - sh build_bee_vm.sh
